name: demo_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  gap: ^3.0.1
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
